### ISSUE TITLE
Factory pattern used incorrectly/unused thus causing problems in creation of new connectors

### ISSUE THREAD

**Issue by sergeylappo** [kovaloid/iresolver#128]
Current implementations of IssueClientFactory in fact does not implement factory pattern.

Factory pattern supposes that factory objects are constructed differently and used using the same interface to construct objects, while current implementation only creates instances of such factories and then uses their methods with custom params.

This would cause code growth in the future after adding additional connectors, which itself might become hardly achievable task

**Comment by kovaloid** [comment]
Done
